In [1]:
import numpy as np

In [6]:
arr = np.array([1,2,3])

In [7]:
arr

array([1, 2, 3])

In [8]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(5)

array([0.74264117, 0.90644816, 0.57263243, 0.05271419, 0.73194659])

In [18]:
np.random.rand(5,4)

array([[0.76572185, 0.72297605, 0.75648397, 0.11792568],
       [0.68209958, 0.82797052, 0.99928156, 0.97500184],
       [0.0905648 , 0.16443005, 0.28211946, 0.03979866],
       [0.37173884, 0.66270452, 0.12694922, 0.08966769],
       [0.32773854, 0.83275097, 0.26836994, 0.21355809]])

In [19]:
np.random.randn(2)

array([ 1.4407627 , -1.03972979])

In [20]:
np.random.randn(4,3)

array([[ 0.45400876, -0.56237307, -0.63362481],
       [-1.98686677, -0.66763149,  0.14340241],
       [-0.87947755,  2.80719434,  0.52336023],
       [-0.30593062,  0.04450007,  0.47628154]])

In [22]:
np.random.randint(4,100, 3)

array([25, 15, 20])

In [23]:
arr = np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0,50,10)

In [28]:
ranarr

array([11, 45, 14, 29,  8, 14,  1, 25, 34, 43])

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
ranarr.max()

45

In [33]:
ranarr.min()

1

In [36]:
ranarr.argmax()

1

In [37]:
ranarr.argmin()

6

In [39]:
ranarr.shape

(10,)

In [42]:
ranarr.reshape(2,5).shape

(2, 5)

In [43]:
arr.dtype

dtype('int32')

# Numpy Indexing

In [44]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr[2]

2

In [47]:
arr[:3]

array([0, 1, 2])

In [48]:
arr[2:4]

array([2, 3])

In [49]:
 arr[0:5]

array([0, 1, 2, 3, 4])

In [51]:
arr[5:][2]

7

In [52]:
arr[0:5] = 100

In [53]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [56]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [59]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [60]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [62]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [63]:
arr_copy[:] = 100

In [64]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [65]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [66]:
arr_2d = np.array([[5,10,15],[20,25,30], [35,40,45]])

In [67]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [69]:
arr_2d[1,0]

20

In [71]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [72]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

# Numpy Operations

In [77]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [79]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [81]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [82]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [84]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [85]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])